[workspace]
members = [
	"frame/ethereum",
	"rpc",
	"rpc/core",
	"rpc/primitives",
	"template/node",
	"template/runtime",
	"template/test-utils/client",
]
exclude = ["vendor"]

[patch.crates-io]
ethereum = { path = "vendor/ethereum" }
