[package]
name = "frontier-template-test-client"
version = "0.1.0"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
description = "Ethereum RPC (web3) compatibility layer for Substrate."
license = "GPL-3.0"

[dependencies]
codec = { package = "parity-scale-codec", version = "1.3.1" }
sp-runtime = { path = "../../../vendor/substrate/primitives/runtime" }
sp-api = { path = "../../../vendor/substrate/primitives/api" }
sc-executor = { path = "../../../vendor/substrate/client/executor" }
sc-light = { path = "../../../vendor/substrate/client/light" }
sc-consensus = { path = "../../../vendor/substrate/client/consensus/common" }
sc-client-api = { path = "../../../vendor/substrate/client/api" }
substrate-test-client = { path = "../../../vendor/substrate/test-utils/client" }
frontier-template-runtime = { path = "../../runtime" }